### ISSUE TITLE
Tracking podofo in downstream package ecosystem

### ISSUE THREAD

**Issue by luzpaz** [podofo/podofo#87]
Noticed that many downstream package repositories are still referencing sourceforge as the destination to retrieve podofo from. So I started letting downstream know. Any help is welcome, perhaps we can ping maintainers from the list below? 

- [x] Conan 
    + (https://github.com/conan-io/conan-center-index/issues/18323) 
    + (https://github.com/conan-io/conan-center-index/pull/27214)
- [ ] [Debian unstable](https://packages.debian.org/sid/source/libpodofo)
- [x] [Fedora Rawhide](https://packages.fedoraproject.org/pkgs/podofo/)
- [x] [gentoo](https://packages.gentoo.org/packages/app-text/podofo)
- [x] homebrew ([discussion](https://github.com/orgs/Homebrew/discussions/4622)) PR: https://github.com/Homebrew/homebrew-core/pull/135848
- [ ] macports (https://trac.macports.org/ticket/67719#ticket)
- [x] [openmamba](https://openmamba.org/en/packages/?tag=devel&pkg=podofo.source)
- [x] [OpenMandriva Rolling](https://github.com/OpenMandrivaAssociation/podofo/tree/rolling)
- [x] [OpenSUSE Tumbleweed](https://build.opensuse.org/package/show/graphics/podofo)
- [x] Void linux (https://github.com/void-linux/void-packages/issues/44846)

<a href="https://repology.org/project/podofo/versions">
    <img src="https://repology.org/badge/vertical-allrepos/podofo.svg?columns=4" alt="Packaging status" >
</a>

**Comment by luzpaz** [comment]
CC @mapreri, sorry for the bump but would it be possible to update podofo in Debian unstable ? :point_up_2: (the package URL needs to change from sourceforge to github)

**Comment by ceztko** [comment]
Hello, thank your for creating this tracking ticket! I'm currently not urging distros/package managers to upgrade, especially since tools are not yet ready to be released (I want to work on them in couple of weeks) and there are more API changes planned for the future, but with 0.10.1 at least there's an hardening update and I'm happy to see more migration happening in the wild! The static website was on sourceforge but since I didn't rush to revamp it I'm now now more inclined to have it here in github as well, so I created a placeholder https://podofo.github.io/ . If and when I will revamp the static website I will drop it there. Updated also the reference to it on github repository page.

**Comment by luzpaz** [comment]
Sorry for jumping the gun on this. Some packages have already been updated so the ball has been set in motion...hopefully that isn't going to be too much of an issue?? :frowning_face:

**Comment by ceztko** [comment]
No issue at all, the only issue is that I am not a big fan of podofo tools and I still didn't have much time to look at them to modernize the code there and put them in a state where I can comfortably support them for small fixes, if required (I won't look at them to add new features or major bug fixing, I'm just not interested in tools). I understand this may be stop some distros from upgrading until there's a clear word on their future. I didn't receive the help I was hoping for in the PoDoFo ML, so I will give them a last try this summer.

**Comment by mapreri** [comment]
> CC @mapreri, sorry for the bump but would it be possible to update podofo in Debian unstable ? point_up_2 (the package URL needs to change from sourceforge to github)

yes of course.  I'm fully aware of the new podofo home and the new release…  just that I somehow got incredibly busy recently.  I'll try to bump my priority here.

**Comment by ceztko** [comment]
Hello @mapreri . I just wanted to inform here that PoDoFo 1.0.0 is coming [soon](https://www.mail-archive.com/podofo-users@lists.sourceforge.net/msg04991.html), featuring some kind of stable API (E.T.A: 1-2 months). At this point I think it may be a good idea to just skip 0.10.x in Debian/Ubuntu and put 1.0.0 in fast track, but I don't know what would be the interaction with other packages depending on PoDofo. Kalibre/Scribus should be the main one: both migrated/added support for 0.10.x already, but they are possibly incompatible with 1.0.0 for now. If you hoped tools to come as well for 1.0.0, I'm sorry but their support state is still indeterminate. I'm confident at some point they may be finally reinstanced, but I can't give any E.T.A. on that at the moment.

**Comment by Malacath-92** [comment]
I've added podofo/0.10.4 in my fork of the conan-center-index. However I am having some issues using it. The test package will fail with link errors:
```
test_package.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static enum PoDoFo::PdfEncryptAlgorithm __cdecl PoDoFo::PdfEncrypt::Ge
tEnabledEncryptionAlgorithms(void)" (__imp_?GetEnabledEncryptionAlgorithms@PdfEncrypt@PoDoFo@@SA?AW4PdfEncryptAlgorithm@2@XZ) referenced in function main [C:\User
s\user\Documents\Projects\conan-center-index\recipes\podofo\all\test_package\build\msvc-194-x86_64-20-debug\test_package.vcxproj]
test_package.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl PoDoFo::PdfPainter::PdfPainter(enum PoDoFo::PdfPainterFlags)"  
(__imp_??0PdfPainter@PoDoFo@@QEAA@W4PdfPainterFlags@1@@Z) referenced in function main [C:\Users\user\Documents\Projects\conan-center-index\recipes\podofo\all\tes 
t_package\build\msvc-194-x86_64-20-debug\test_package.vcxproj]
test_package.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl PoDoFo::PdfPainter::~PdfPainter(void)" (__imp_??1PdfPainter@Po 
DoFo@@QEAA@XZ) referenced in function main [C:\Users\user\Documents\Projects\conan-center-index\recipes\podofo\all\test_package\build\msvc-194-x86_64-20-debug\te 
st_package.vcxproj]
```

This seems to imply that `PODOFO_STATIC` is not defined, but it's unclear to me whether this should be defined by clients or if there should be some mechanism to define it through the cmake declared link targets. If I try to manually define `PODOFO_STATIC` I get other link errors.

I would appreciate some guidance on this issue and will gladly share any more to help you help me.
The recipe (largely overlapping with 0.9.7) can be found here: https://github.com/Malacath-92/conan-center-index/tree/podofo-0.10.4/recipes/podofo
To test it one can open a command prompt in the `recipes` folder and run the following command
```
conan create podofo/all --version=0.10.4 --build=missing
```
I use a new version of MSVC so I additionally added `-s compiler.version=194`

**Comment by Malacath-92** [comment]
I just found the instructions that stated that clients indeed have to define `PODOFO_STATIC` themselves, and they also have to link with `podofo_private`. I can't say I agree with that setup, why does `podofo_static` (aliased to `podofo::podofo`) not define/link these automatically? I will try to patch this behavior and see if that works for me, unless you have a specific reason not to try that.

**Comment by ceztko** [comment]
@Malacath-92 : Please read: https://github.com/podofo/podofo?tab=readme-ov-file#static-linking

Also notice:
> If you are linking against a precompiled static build of PoDoFo this is a scenario where the support is limited, as you are really supposed to be able to identify and fix linking errors. 

You wrote:
>  I can't say I agree with that setup, why does podofo_static (aliased to podofo::podofo) not define/link these automatically?

Well, only CMake can help here in linking transitive dependencies. If you don't use CMake then it's exactly how I wrote. If you use CMake, try to see if it's enough to do `target_link_libraries(your_target podofo_static)`.

**Comment by Malacath-92** [comment]
Like I said in my second post I found those instructions and applied them successfully.

> Well, only CMake can help here in linking transitive dependencies. If you don't use CMake then it's exactly how I wrote.
I'm by no means a conan savant, but my impression was that linking happens via CMake. But perhaps everything in the end going through `find_package` and using the returned target does not preserve the original dependency chain.
Even if the linkage of `pdofo_private` was fixed through the intended mechanism in CMake, the client would still have to define `PODOFO_STATIC`, or perhaps I am just missing the mechanism through which this is not needed.

Either way this is probably the wrong place to have this discussion. I will open a PR with the conan team and see if they can help me figure out the rest.

**Comment by luzpaz** [comment]
Looks like Arch Linux is being held up.

**Comment by ceztko** [comment]
1.0.0 will be released together with 0.10.5 in few (couple?) of days. I will post some updates in the ML mentioning the lifecycle policies for future PoDoFo releases and make a link to that post here.

**Comment by ceztko** [comment]
Hello @mapreri ! Do you have any update for the debian/ubuntu PoDoFo package upgrade? Is there any issue? Consider I urged 1.0 release to leave enough time for packaging hoping for a Ubuntu 26.04 inclusion. I understand that the exclusion of the PoDoFo tools may represent an issue, but I guess it's easy enough to keep redistributing 0.9.8 libraries as a separate package to run the legacy tools, and switching `libpodofo-dev` to install the new 1.0 library and header.

**Comment by luzpaz** [comment]
Congrats on the 1.0.0-1.0.1 release. IMHO this ticket can be closed.

**Comment by ceztko** [comment]
> IMHO this ticket can be closed.

Ok. I still hope to hear good news from Debian/Ubuntu soon.
